version: "3.9"

services:
  web:
    build: ./web
    command: gunicorn web.trucker_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      -  8000

  nginx:
    build: ./nginx
    command: nginx -g "daemon off;"
    volumes:
       - .:/code
    restart: always
    ports:
       -  443:443
       -  80:80
    depends_on:
       -  web

